name: chatwork

on:
  pull_request:
    types:
      - opened
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          chatwork-api-token: "0924c452f45341fe656254727dac98ca"
          chatwork-room-id: "227803817"
          mapping: |
            {
              "daint-1849": 3844173,
              "dai-dev-demo": 5827977
            }
